# Generated by Django 2.2.3 on 2019-07-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_testchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pub_date',
        ),
    ]
